//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatcherService.Classes.PlanAppoints {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DispatcherService.Classes.PlanAppoints.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select DriverName, DriverPhone from DocAppoints where trackMark like @trackMark and licensePlate like @licensePlate order by id desc.
        /// </summary>
        internal static string DriverList {
            get {
                return ResourceManager.GetString("DriverList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select licensePlate from docAppoints where trackMark like @trackMark ||&apos;%&apos; group by licensePlate order by licensePlate.
        /// </summary>
        internal static string LicensePlateList {
            get {
                return ResourceManager.GetString("LicensePlateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from planAppoints where id = @id.
        /// </summary>
        internal static string QueryDelete {
            get {
                return ResourceManager.GetString("QueryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into PlanAppoints (id, idUnit, trackMark, licensePlate, driverName, driverPhone, planDate, cargo, notes, isClosed) values (@id, @idUnit, @trackMark, @licensePlate, @driverName, @driverPhone, @planDate, @cargo, @notes, @isClosed) returning id.
        /// </summary>
        internal static string QueryInsert {
            get {
                return ResourceManager.GetString("QueryInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select planAppoints.*, NULL as dateAppoint from planAppoints where id = @id.
        /// </summary>
        internal static string QuerySelect {
            get {
                return ResourceManager.GetString("QuerySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select pl.*, st.dateState as dateAppoint from planAppoints pl left join DocAppoints app on (app.planAppoint = pl.id) left join docAppointStates st on (st.Appoint = app.id and st.docState = 0) where planDate between @dateFrom and @dateTo order by planDate.
        /// </summary>
        internal static string QuerySelectList {
            get {
                return ResourceManager.GetString("QuerySelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update planAppoints set idUnit = @idUnit, trackMark = @trackMark, licensePlate = @licensePlate, driverName = @driverName, driverPhone = @driverPhone, planDate = @planDate, cargo = @cargo, notes = @notes, isClosed = @isClosed where id = @id.
        /// </summary>
        internal static string QueryUpdate {
            get {
                return ResourceManager.GetString("QueryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select planAppoints.*, NULL as dateAppoint from PlanAppoints where id not in (select planAppoint from DocAppoints where planAppoint is not null) and isClosed = 0 order by planDate.
        /// </summary>
        internal static string SelectFullList {
            get {
                return ResourceManager.GetString("SelectFullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select trackMark from docAppoints group by trackMark order by trackMark.
        /// </summary>
        internal static string TrackMarkList {
            get {
                return ResourceManager.GetString("TrackMarkList", resourceCulture);
            }
        }
    }
}
